version: '3'

volumes:
  rabbitmq_data:

services:

###################################
  # Update Appointment: The Update Appointment microservice
  ###################################
  updateappointment:
    build:
      context: ./
      dockerfile: updateappointment.Dockerfile
    image: updateappointment
    ports:
      - "5008:5008"
    restart: always
    environment:
      DB_URL: mysql+mysqlconnector://root:root@host.docker.internal:8889/APPOINTMENTDB
      PYTHONUNBUFFERED: 1

  appointmentcreator:
    build:
      context: ./
      dockerfile: appointmentcreator.Dockerfile
    image: appointmentcreator
    ports:
      - "5007:5007"
    restart: always
    depends_on:
      - updateappointment
    environment:
      PYTHONUNBUFFERED: 1
